export const USER_ACTION_TYPES = {
  USER_SUCCESS: "USER_SUCCESS",
  USER_START: "USER_START",
  USER_FAIL: "USER_FAIL",
  USER_LOGOUT: "USER_LOGOUT",
  USER_LOGOUT_START: "USER_LOGOUT_START",
  ESTABLISH_SOCKET_CONNECTION: "ESTABLISH_SOCKET_CONNECTION",
  USER_INVITE_SUCCESS: "USER_INVITE_SUCCESS",
  USER_DELETE_INVITE_SUCCESS: "USER_DELETE_INVITE_SUCCESS",
  USER_INVITE_START: "USER_INVITE_START",
  USER_INVITE_FAIL: "USER_INVITE_FAIL",
};
