export const CHAT_ACTION_TYPES = {
  FETCH_CHATS_START: "FETCH_CHATS_START",
  FETCH_CHATS_SUCCESS: "FETCH_CHATS_SUCCESS",
  FETCH_CHATS_FAILED: "FETCH_CHATS_FAILED",
  SAVE_USER: "SAVE_USER",
  CHANGE_CURRENT_CHAT: "CHANGE_CURRENT_CHAT",
  CREATE_CHAT_START: "CREATE_CHAT_START",
  CREATE_CHAT_SUCCESS: "CREATE_CHAT_SUCCESS",
  CREATE_CHAT_FAILED: "CREATE_CHAT_FAILED",
};
